name: Compile Resume
on:
  push:
    branches: [ main ]
jobs:
  compile:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    steps:
      - uses: actions/checkout@v4
      - run: make
      - uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: resume.pdf
